version: '3.9'
services:
  justice_juggernaut: 
    profiles: ["no-proxy"]
    container_name: justice_juggernaut
    image: storminstakk/justice_juggernaut
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=DISABLE_GPT4

  justice_juggernaut-proxy: 
    profiles: ["proxy"]
    container_name: justice_juggernaut-proxy
    image: storminstakk/justice_juggernaut
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - CODE=$CODE
      - PROXY_URL=$PROXY_URL
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=DISABLE_GPT4