version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor:
      name: node/default
      tag: '14.17.6'

    working_directory: ~/Justice_Juggernaut-main

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: npm run build

  test:
    executor:
      name: node/default
      tag: '14.17.6'

    working_directory: ~/Justice_Juggernaut-main

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: npm test

  lint:
    executor:
      name: node/default
      tag: '14.17.6'

    working_directory: ~/Justice_Juggernaut-main

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build

